# Generated by Django 5.0.7 on 2025-03-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_rename_total_price_sale_prices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
    ]
