# Generated by Django 5.0.7 on 2025-03-25 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_sale_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total_amount',
            new_name='total_price',
        ),
    ]
