# Generated by Django 5.0.7 on 2025-04-11 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_rename_total_amount_sale_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='customer',
            new_name='Customer',
        ),
    ]
