# Generated by Django 5.0.7 on 2025-04-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_rename_customer_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='prescription',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
