# Generated by Django 5.0.7 on 2025-04-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_delete_expense_delete_purchaseorder_delete_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='prescription',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacy/static/prescription_images'),
        ),
    ]
