# Generated by Django 5.0.7 on 2025-04-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_finance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance',
            old_name='Monthly_Revenue',
            new_name='monthly_revenue',
        ),
    ]
