# Generated by Django 5.0.7 on 2025-04-22 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_rename_monthly_revenue_finance_monthly_revenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance',
            old_name='monthly_revenue',
            new_name='Revenue',
        ),
    ]
