# Generated by Django 5.0.7 on 2025-04-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_rename_monthly_revenue_finance_revenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='price',
            new_name='Buyingprice',
        ),
        migrations.AddField(
            model_name='medicine',
            name='Saleprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
