# Generated by Django 5.0.7 on 2025-04-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_rename_price_medicine_buyingprice_medicine_saleprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='manufacturer',
            new_name='supplier',
        ),
    ]
