# Generated by Django 5.0.7 on 2025-04-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_rename_manufacturer_medicine_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='Saleprice',
            new_name='saleprice',
        ),
    ]
