# Generated by Django 5.0.7 on 2025-04-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_rename_saleprice_medicine_saleprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='Buyingprice',
            new_name='buyingprice',
        ),
    ]
