# Generated by Django 5.0.7 on 2025-04-25 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0018_doctors_tickets_day_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='Doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.doctors'),
            preserve_default=False,
        ),
    ]
