# Generated by Django 5.0.7 on 2025-04-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0019_tickets_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='order',
            field=models.IntegerField(null='True'),
        ),
    ]
