# Generated by Django 5.0.7 on 2025-04-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0020_alter_tickets_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='order',
        ),
    ]
