# Generated by Django 5.0.7 on 2025-04-26 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0021_remove_tickets_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='Doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.doctors'),
        ),
    ]
