# Generated by Django 5.0.7 on 2025-04-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0022_alter_tickets_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='day_time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', max_length=100),
        ),
    ]
