# Generated by Django 5.0.7 on 2025-04-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0023_alter_tickets_day_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='contact_number',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='Doctor',
            field=models.CharField(choices=[('Jamac', 'Jamac'), ('Ismail', 'Ismail'), ('Khalid', 'Khalid')], default='Ismail', max_length=100),
        ),
    ]
