# Generated by Django 5.0.7 on 2025-04-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0024_remove_tickets_contact_number_alter_tickets_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='Doctor',
            new_name='doctor',
        ),
    ]
